title: 뚜시뚜시 블로그
page-title: 정리용 블로그
home-title: 
description: 
url: 'https://ddusy.github.io/'
nav:
  Home: /
  Tags: /tags/
  Timeline: /timeline/
  About: /about/
  reLink: /reLink/
author: true
name: 
NickName: 뚜시뚜시
webtitle: 뚜시뚜시 블로그
bio: 안녕하세요! 
about: true
aboutyou: "  "
portraits: /assets/GitBlogImg.jpg
honorificPrefix: '***'
image: /assets/GitBlogImg.png
familyname:
honorificSuffix: King
disambiguatingDescription: Your awesome description
birthPlace: Your address
birthDate: Your Date of Birth
height: XX inches
gender: Your gender
memberOf: Your awesome orgranization
nationality: Your proud nationality
jobTitle: Your Respectful Position
knowsAbout: Your awesome Skill
knowsLanguage: ''
worksFor:
  type: LocalBusiness
  name: ''
  openingHours: 'Sa-Fr 09:00-21:00'
  priceRange: $$$
  telephone:
    - +8801XXXXXXXX
    - +8801XXXXXXXXX
  image: 'https://i.imgur.com/BGBJWBq.png'
  address:
    type: PostalAddress
    addressCountry: ''
    addressLocality: ''
    addressRegion: ''
future: true
SNS: true
SNS-icon:
  mail: 'dkdnb50@gmail.com'
  github: 'https://github.com/DDusy'
permalink: '/blog/:title/'
paginate: 4
paginatepath:
  - 'page:num'
footer:
  since: 2018
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygmentsTheme: default
# disqus  
disqus: true
disqus_url: 'https://https-ddusy-github-io.disqus.com/embed.js'
livere: false
livere_uid: MTAyMC8zNDI2OS8xMDgwNg==
Gitment: false
Gitment_owner: 'DDusy'
Gitment_repo: 'https://github.com/DDusy/DDusy.github.io'
social-share: true
social-share-items:
baidu: false
baidu-url: ''
google: true
google-ID: <UA-42070905-2>
color: 'rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)'
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji
whitelist:
  - jekyll-redirect-from
logo: /assets/banner.png
twitter:
  username: your_name
  card: summary
social:
  name: your_name
  links:
    - 'mailto:yourname@example.com'
    - 'https://github.com/example'
    - 'https://codepen.io/example/#'
    - 'https://twitter.com/@example'
    - 'https://www.instagram.com/example/'
    - 'https://facebook.com/example'
    - 'https://plus.google.com/+example'
webmaster_verifications:
  google: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
exclude:
  - screenshot
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - '*.Rmd'
  - .git*
  - package-lock.json
  - gulpconfig.json

