 # Site settings Configuring the site
title : ' your awesome title '
 description : ' your web description '
 keywords : ' your web keywords, another keywords '
 url : ' https://DDusy.github.io '

#Author/Blogger
NickName: 'DDusy'
webtitle: '끄적끄적'
bio: 'Student, Computer Programmer And a Scented Soul'
about: true
aboutyou: "
          your awesome story <br>
          use br tag for new line <br>
          and &\emsp for Chinese space
          "
portraits: '/assets/madara.png' # your portraits image file path

layout: post
title:  "post title"
subtitle: 'post subtitle'
date:   2018-05-29 08:44:13
tags: html js css
description: ''
color: 'rgb(154,133,255)'
cover: ''
typora-root-url: ".."

layout: default
title: 타이틀 테스트
page-title: awesome page-title.
home-title: awesome home-title.
description: description
